[player,1,["ACE_SelfActions","COptions","Commander"]] call ace_interact_menu_fnc_removeActionFromObject;
//[player,1,["ACE_SelfActions","COptions","SubCommander"]] call ace_interact_menu_fnc_removeActionFromObject;
[command] call H_fnc_setUpCommand;
[arty] call H_fnc_setUpArty;
[mt] call H_fnc_setUpMT;
[air] call H_fnc_setUpAir;
[arm] call H_fnc_setUpArmourer;
[player, 1, ["ACE_SelfActions","COptions"],H_action_saveMission] call ace_interact_menu_fnc_addActionToObject;
[player, 1, ["ACE_SelfActions","COptions"],H_action_saveMissionExit] call ace_interact_menu_fnc_addActionToObject;
[player, 1, ["ACE_SelfActions","COptions"],H_action_commanderResign] call ace_interact_menu_fnc_addActionToObject;